Areas/English/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fun2tw.Models;
using Fun2twModels.Models;

namespace Fun2tw.Areas.English.Controllers
{
    public class NavigationController : Controller
    {
        private BackendContext _db = new BackendContext();

        //
        // GET: /Navigation/

        public ActionResult Index()
        {
            return View(_db.Navigations.ToList());
        }



        public ActionResult AddLocation(string Subject, string Address, string Lon, string Lat)
        {

            List<Navigation> addressList;

            String result;
            if (Session["addressList"] == null)
            {
                addressList = new List<Navigation>();
            }
            else
            {
                addressList = (List<Navigation>)Session["addressList"];
            }

            //重複加入
            if (addressList.Any(x=>x.Subject==Subject))
            {
                result = "duplicate";
            }
            else if (addressList.Count >= 10)
            {
                result = "over";
            }
            else
            {
                var navigation = new Navigation
                {
                    Subject = Subject,
                    Address = Address,
                    Lat = Lat,
                    Lon = Lon
                };


                addressList.Add(navigation);
                result = addressList.Count.ToString();
            }

            Session["addressList"] = addressList;
            return Content(result);
        }




        //public ActionResult SortLocation(int[] location)
        //{
        //    if (location == null)
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    if (location.Length == 1)
        //    {
        //        ViewBag.Message = "請選擇兩個景點以上";
        //    }
        //    if (location.Length > 10)
        //    {
        //        ViewBag.Message = "Google MAP 僅支援10個景點內路線規劃";

        //    }
        //    var navigation = _db.Navigations.Where(x => location.Contains(x.Id)).ToList();
        //    return View(navigation.ToList());
        //}

        public ActionResult SortLocation()
        {
            List<Navigation> addressList;

            if (Session["addressList"] == null)
            {
                addressList = new List<Navigation>();
            }
            else
            {
                addressList = (List<Navigation>)Session["addressList"];
            }


            if (addressList.Count <= 1)
            {
                ViewBag.Message = "請選擇兩個以上的景點";
            }
            if (addressList.Count > 10)
            {
                ViewBag.Message = "Google MAP 僅支援10個景點內路線規劃";
            }




            return View(addressList);
        }


        //[HttpPost]
        //public ActionResult Result(string[] address)
        //{

        //    //Some code..........
        //    List<string> addressList = new List<string>();
        //    foreach (string location in address)
        //    {
        //        addressList.Add(location);
        //    }
        //    ViewBag.Address = addressList;

        //    return View();
        //    //return View(addressList);
        //}

        public ActionResult Result(List<TravelNavigation> travel,string isSave="")
        {
            if (travel == null)
            {
                return RedirectToAction("SortLocation");
            }
            List<int> addressList=new List<int>();
            foreach (var item in travel.OrderBy(x=>x.listNum))
            {
                addressList.Add(item.id);
            }
            //Session["addressList"] = addressList;

            ViewBag.isSave = isSave;
            return View(travel);
        }


        //
        // GET: /Navigation/Delete/5

        public ActionResult Remove(int id = 0)
        {
            List<int> addressList;
            if (Session["addressList"] == null)
            {
                addressList = new List<int>();
            }
            else
            {
                addressList = (List<int>)Session["addressList"];
            }

            addressList.Remove(id);

            Session["addressList"] = addressList;

            return RedirectToAction("SortLocation");
        }

        public ActionResult OverView()
        {

            return View();
        }

        public ActionResult Plan()
        {

            return View();
        }

        [Authorize]
        public ActionResult Save()
        {
            List<int> addressLists;
            if (Session["addressList"] == null)
            {
                return RedirectToAction("Plan");
            }

            addressLists = (List<int>)Session["addressList"];

            string DetailsIDs = "";
            foreach (int item in addressLists)
            {
                DetailsIDs += item.ToString() + " ";
            }
            CustomerLocation location = new CustomerLocation();
            location.DetailsIDs = DetailsIDs.Trim();
            Customers customers = _db.Customerses.FirstOrDefault(x => x.Account == User.Identity.Name);
            location.CustomerId = customers.Id;

            int[] locationarray = addressLists.ToArray();
            var travelplans = _db.TravelPlans.Where(x => locationarray.Contains(x.Id)).ToList();

            List<TravelPlan> paList=new List<TravelPlan>();
            foreach (int item in addressLists)
            {

                var newitem = travelplans.FirstOrDefault(x => x.Id == item);
                paList.Add(newitem);
            }


            ViewBag.travelplans = paList;

            return View(location);



        }

        [Authorize]
        [HttpPost]
        public ActionResult Save(CustomerLocation location)
        {
            location.InitDate = DateTime.Now;
            _db.CustomerLocations.Add(location);
            _db.SaveChanges();

            return RedirectToAction("MyLocaltion");
        }

        [Authorize]
        public ActionResult MyLocaltion()
        {
            Customers customers = _db.Customerses.FirstOrDefault(x => x.Account == User.Identity.Name);


            return View(customers.CustomerLocations.OrderByDescending(x=>x.InitDate).ToList());
        }

        [Authorize]
        public ActionResult MyLocaltionDetails(int id = 0)
        {
            List<int> addressList;
            CustomerLocation customerLocation = _db.CustomerLocations.Find(id);
            if (customerLocation == null)
            {
                return RedirectToAction("MyLocaltion");
            }


            //int[] location = Array.ConvertAll(addressList.ToArray(), s => int.Parse(s)); 
            string[] DetailsIDs = customerLocation.DetailsIDs.Split(' ');
            List<int> addressLists = new List<int>();
            foreach (string detailsID in DetailsIDs)
            {
                addressLists.Add(Convert.ToInt16(detailsID) );
            }
            int[] locationarray = addressLists.ToArray();
            var travelplans = _db.TravelPlans.Where(x => locationarray.Contains(x.Id)).ToList();
            List<TravelPlan> paList = new List<TravelPlan>();
            foreach (int item in addressLists)
            {

                var newitem = travelplans.FirstOrDefault(x => x.Id == item);
                paList.Add(newitem);
            }
            return View(paList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteLocation(int id)
        {
            CustomerLocation location = _db.CustomerLocations.Find(id);
            _db.CustomerLocations.Remove(location);
            _db.SaveChanges();
            return RedirectToAction("MyLocaltion");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Areas/Japan/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fun2tw.Models;
using Fun2twModels.Models;

namespace Fun2tw.Areas.Japan.Controllers
{
    public class NavigationController : Controller
    {
        private BackendContext _db = new BackendContext();

        //
        // GET: /Navigation/

        public ActionResult Index()
        {
            return View(_db.Navigations.ToList());
        }



        public ActionResult AddLocation(string Subject, string Address, string Lon, string Lat)
        {

            List<Navigation> addressList;

            String result;
            if (Session["addressList"] == null)
            {
                addressList = new List<Navigation>();
            }
            else
            {
                addressList = (List<Navigation>)Session["addressList"];
            }

            //重複加入
            if (addressList.Any(x=>x.Subject==Subject))
            {
                result = "duplicate";
            }
            else if (addressList.Count >= 10)
            {
                result = "over";
            }
            else
            {
                var navigation = new Navigation
                {
                    Subject = Subject,
                    Address = Address,
                    Lat = Lat,
                    Lon = Lon
                };


                addressList.Add(navigation);
                result = addressList.Count.ToString();
            }

            Session["addressList"] = addressList;
            return Content(result);
        }




        //public ActionResult SortLocation(int[] location)
        //{
        //    if (location == null)
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    if (location.Length == 1)
        //    {
        //        ViewBag.Message = "請選擇兩個景點以上";
        //    }
        //    if (location.Length > 10)
        //    {
        //        ViewBag.Message = "Google MAP 僅支援10個景點內路線規劃";

        //    }
        //    var navigation = _db.Navigations.Where(x => location.Contains(x.Id)).ToList();
        //    return View(navigation.ToList());
        //}

        public ActionResult SortLocation()
        {
            List<Navigation> addressList;

            if (Session["addressList"] == null)
            {
                addressList = new List<Navigation>();
            }
            else
            {
                addressList = (List<Navigation>)Session["addressList"];
            }


            if (addressList.Count <= 1)
            {
                ViewBag.Message = "請選擇兩個以上的景點";
            }
            if (addressList.Count > 10)
            {
                ViewBag.Message = "Google MAP 僅支援10個景點內路線規劃";
            }




            return View(addressList);
        }


        //[HttpPost]
        //public ActionResult Result(string[] address)
        //{

        //    //Some code..........
        //    List<string> addressList = new List<string>();
        //    foreach (string location in address)
        //    {
        //        addressList.Add(location);
        //    }
        //    ViewBag.Address = addressList;

        //    return View();
        //    //return View(addressList);
        //}

        public ActionResult Result(List<TravelNavigation> travel,string isSave="")
        {
            if (travel == null)
            {
                return RedirectToAction("SortLocation");
            }
            List<int> addressList=new List<int>();
            foreach (var item in travel.OrderBy(x=>x.listNum))
            {
                addressList.Add(item.id);
            }
            //Session["addressList"] = addressList;

            ViewBag.isSave = isSave;
            return View(travel);
        }


        //
        // GET: /Navigation/Delete/5

        public ActionResult Remove(int id = 0)
        {
            List<int> addressList;
            if (Session["addressList"] == null)
            {
                addressList = new List<int>();
            }
            else
            {
                addressList = (List<int>)Session["addressList"];
            }

            addressList.Remove(id);

            Session["addressList"] = addressList;

            return RedirectToAction("SortLocation");
        }

        public ActionResult OverView()
        {

            return View();
        }

        public ActionResult Plan()
        {

            return View();
        }

        [Authorize]
        public ActionResult Save()
        {
            List<int> addressLists;
            if (Session["addressList"] == null)
            {
                return RedirectToAction("Plan");
            }

            addressLists = (List<int>)Session["addressList"];

            string DetailsIDs = "";
            foreach (int item in addressLists)
            {
                DetailsIDs += item.ToString() + " ";
            }
            CustomerLocation location = new CustomerLocation();
            location.DetailsIDs = DetailsIDs.Trim();
            Customers customers = _db.Customerses.FirstOrDefault(x => x.Account == User.Identity.Name);
            location.CustomerId = customers.Id;

            int[] locationarray = addressLists.ToArray();
            var travelplans = _db.TravelPlans.Where(x => locationarray.Contains(x.Id)).ToList();

            List<TravelPlan> paList=new List<TravelPlan>();
            foreach (int item in addressLists)
            {

                var newitem = travelplans.FirstOrDefault(x => x.Id == item);
                paList.Add(newitem);
            }


            ViewBag.travelplans = paList;

            return View(location);



        }

        [Authorize]
        [HttpPost]
        public ActionResult Save(CustomerLocation location)
        {
            location.InitDate = DateTime.Now;
            _db.CustomerLocations.Add(location);
            _db.SaveChanges();

            return RedirectToAction("MyLocaltion");
        }

        [Authorize]
        public ActionResult MyLocaltion()
        {
            Customers customers = _db.Customerses.FirstOrDefault(x => x.Account == User.Identity.Name);


            return View(customers.CustomerLocations.OrderByDescending(x=>x.InitDate).ToList());
        }

        [Authorize]
        public ActionResult MyLocaltionDetails(int id = 0)
        {
            List<int> addressList;
            CustomerLocation customerLocation = _db.CustomerLocations.Find(id);
            if (customerLocation == null)
            {
                return RedirectToAction("MyLocaltion");
            }


            //int[] location = Array.ConvertAll(addressList.ToArray(), s => int.Parse(s)); 
            string[] DetailsIDs = customerLocation.DetailsIDs.Split(' ');
            List<int> addressLists = new List<int>();
            foreach (string detailsID in DetailsIDs)
            {
                addressLists.Add(Convert.ToInt16(detailsID) );
            }
            int[] locationarray = addressLists.ToArray();
            var travelplans = _db.TravelPlans.Where(x => locationarray.Contains(x.Id)).ToList();
            List<TravelPlan> paList = new List<TravelPlan>();
            foreach (int item in addressLists)
            {

                var newitem = travelplans.FirstOrDefault(x => x.Id == item);
                paList.Add(newitem);
            }
            return View(paList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteLocation(int id)
        {
            CustomerLocation location = _db.CustomerLocations.Find(id);
            _db.CustomerLocations.Remove(location);
            _db.SaveChanges();
            return RedirectToAction("MyLocaltion");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Navigation/Index.cshtml
@using Fun2twModels.Models
@model IEnumerable<Fun2twModels.Models.Navigation>

@{
    ViewBag.Title = "墾丁交通-瘋趣台灣-路線規劃-選擇景點";
}
@section description
{
    <meta name="description" content="屏東客運‧屏東旅行社全新打造瘋趣台灣─墾丁好行4G智慧旅遊服務，提供墾丁快線網路預約、車輛動態查詢、墾丁路線規劃，車上空位查詢，墾丁交通資訊一把抓- 立即預訂車票-" />
}
<script>
    jQuery(document).ready(function($) {
        $('.table tr').click(function(){
 var checkBoxes = $(this).find('input');
 checkBoxes.attr("checked", !checkBoxes.attr("checked"));
})
    });
</script>
<style>
    
    .table tr:hover{
background:#008DD8 !important;color:#fff;    }
</style>
<div class="container" style="display:none">
    @*@{
        List<Navigation> navigation = ViewBag;
    }*@
    
    @using (Html.BeginForm("SortLocation", "Navigation")){
         
          @Html.ValidationSummary(true)
          <div class="container">
              
          </div>
          <h2 class="l-title">
            <i class="fa fa-map-marker"></i> 路線規劃 
          </h2>
        <h3>請選擇要規劃路線的景點</h3>
    <table class="table table-striped" id="LocalTable">
        <tr>
            <th width="5%">選擇</th>
            <th width="30%">
                景點名稱
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
        </tr>
        <tbody>
        @*注意這邊,要指定排序*@
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input  type="checkbox" name="location" value="@item.Id"/>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
            </tr>
        }
        </tbody>
    </table>

 
        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="下一步" class="btn-button"/>
        </div>
    }
</div>



@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortMemo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Poster)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InitDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updater)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortMemo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Poster)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InitDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Updater)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@

Views/Navigation/MyLocaltion.cshtml
@using Fun2twModels.Models
@model List<Fun2twModels.Models.CustomerLocation>
@{
    ViewBag.Title = "墾丁交通-瘋趣台灣-我的路線規劃";
}
@section description
{
    <meta name="description" content="屏東客運‧屏東旅行社全新打造瘋趣台灣─墾丁好行4G智慧旅遊服務，提供墾丁快線網路預約、車輛動態查詢、墾丁路線規劃，車上空位查詢，墾丁交通資訊一把抓- 立即預訂車票-" />
}
<style>
    
   .table tr:active{
background:#008DD8 !important;color:#fff;    }
</style>




        <div class="error" >
            <div class="container err-container" style="display:none;height:800px" >
             <h2 class="l-title">
            <i class="fa fa-map-marker">資料錯誤</i>
          </h2>
                <p class="jq-content">@ViewBag.Message</p>
                
          
            </div>

        </div>
        
        <div class="container block-container l-white news-content">
        <h2 class="l-title">
            <i class="fa fa-map-marker"></i>我的路線規劃 
          </h2>

         
       
           
            <table class="table table-striped" id="LocalTable">
                <tr>
                    <th width="30%">
                       行程名稱名稱
                    </th>
                    <th>
                       路線規劃
                    </th>
               
                     <th>
                       
                    </th>
                </tr>
                <tbody>


              
                @*注意這邊,要指定排序*@
                   
                @foreach (var item in Model)
                {
                    <tr>
                        <td>

                          
                          
                            @* @Html.DisplayFor(modelItem => item.Id)*@
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>
                        <td>
                          <a class="btn btn-success" href="/Navigation/MyLocaltionDetails/@item.Id">路線規劃</a> 
                        </td>
                        <td>
                                                        @using (Html.BeginForm("DeleteLocation", "Navigation"))
                            {
                                @Html.AntiForgeryToken()
                                
                                    <input type="submit" value="刪除" onclick="javascript: if (!window.confirm('你確定要刪除嗎?')) window.event.returnValue = false;" class="btn btn-primary" />
                                

                                @*這邊也有改*@
                                @Html.Hidden("id", item.Id)
                            }
                        </td>
                       
                    </tr>
                   
                }
                </tbody>
            </table>
            
          
        </div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

  

    
}

Views/Navigation/MyLocaltionDetails.cshtml
@using Fun2twModels.Models
@model IEnumerable<Fun2twModels.Models.TravelPlan>

@{
    ViewBag.Title = "墾丁交通-瘋趣台灣-路線規劃-景點排序";
}
@section description
{
    <meta name="description" content="屏東客運‧屏東旅行社全新打造瘋趣台灣─墾丁好行4G智慧旅遊服務，提供墾丁快線網路預約、車輛動態查詢、墾丁路線規劃，車上空位查詢，墾丁交通資訊一把抓- 立即預訂車票-" />
}
<style>
    
   .table tr:active{
background:#008DD8 !important;color:#fff;    }
</style>

    @using (Html.BeginForm("Result", "Navigation"))
    {
        <script>
            $(document).ready(function() {
                $("#mode").val('DRIVING');
                $(".driving").click(function() {
                    // alert($(this).attr('data-val'));
                    $("#mode").val($(this).attr('data-val'));
                });
                $('.driving').click(function(event) {
                    /* Act on the event */
                    $(this).addClass('btn-primary').siblings().removeClass('btn-primary');
                });
                if($('.jq-content').text() != ''){
                    $('.block-container').hide();
                    $('.error .err-container').show();
                }
            });
        </script>
        <div class="error" >
            <div class="container err-container" style="display:none;height:800px" >
             <h2 class="l-title">
            <i class="fa fa-map-marker">資料錯誤</i>
          </h2>
                <p class="jq-content">@ViewBag.Message</p>
                
            <div class="text-center">
               
            
                    <input type="button" value="回上一步" class="btn btn-primary" onclick="history.back()"/>
              

            </div>
            </div>

        </div>
        
        <div class="container block-container l-white news-content">
        <h2 class="l-title">
            <i class="fa fa-map-marker"></i>路線規劃 
          </h2>
            <h3>選擇交通工具：<div class="btn-group" role="group" >
              <button type="button" data-val="DRIVING" class="btn btn-default btn-primary driving"><i class="fa fa-car"></i>&nbsp;開車</button>
              <button type="button" data-val="WALKING" class="btn btn-default driving"><i class="fa fa-male"></i>&nbsp;步行</button>
              <button type="button" data-val="TRANSIT" class="btn btn-default driving"><i class="fa fa-subway"></i>&nbsp;大眾運輸</button>
            </div></h3>
            @* <select id="mode" name="mode">
                <option value="DRIVING">開車</option>
                <option value="WALKING">步行</option>
                <option value="BICYCLING">自行車</option>
                <option value="TRANSIT">大眾運輸</option>
            </select>*@
            
            
            <p>
                <span style="color: red"><i class="fa fa-exclamation-circle"></i>&nbsp;注意：選擇大眾運輸只會顯示起點到終點的路線規劃</span>
            </p>
           <input type="hidden" name="mode" id="mode" value="DRIVING"/>
        <h2 class="l-title">
            <i class="fa fa-map-marker"></i>拖曳排序規劃路線
          </h2>
           
            <table class="table table-striped" id="LocalTable">
                <tr>
                    <th width="30%">
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Street)
                    </th>
                   @* <th>
                        @Html.DisplayNameFor(model => model.Lon)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Lat)
                    </th>*@
                     
                </tr>
                <tbody>


                @if (Model.Count() == 0)
                {
                    <tr><td>沒有加入任何景點</td></tr>
                }

                @*注意這邊,要指定排序*@
                    @{
                        int i = 0;
                    }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>

                            <input type="hidden" name="travel[@i].address" value="@item.Subject"/>
                            <input type="hidden" name="travel[@i].Lon" value="@item.Lon"/>
                            <input type="hidden" name="travel[@i].Lat" value="@item.Lat"/>
                             <input type="hidden" name="travel[@i].listNum" value="@i" class="position"/>
                            @* @Html.DisplayFor(modelItem => item.Id)*@
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Street)
                        </td>
                       @* <td>
                            @Html.DisplayFor(modelItem => item.Lon)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lat)
                        </td>*@
                        
                    </tr>
                    i++;
                }
                </tbody>
            </table>
            
            <div class="text-center">
          
                @if (Model.Count() > 1)
                {
                    <input type="hidden" name="isSave" value="true"/>
                    <input type="submit" id="xSubmit" value="規劃路線" class="btn btn-primary"/>
                }
                else
                {
                    <input type="button" value="回上一步" class="btn btn-primary" onclick="history.back()"/>
                }

            </div>
        </div>
    }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="@Url.Content("~/Scripts/jquery.tablednd.0.5.js")" type="text/javascript"></script>

   
}

Views/Navigation/Plan.cshtml
@{
    ViewBag.Title = "墾丁交通-瘋趣台灣-墾丁好行";
}
@section description
{
    <meta name="description" content="屏東客運‧屏東旅行社全新打造瘋趣台灣─墾丁好行4G智慧旅遊服務，提供墾丁快線網路預約、車輛動態查詢、墾丁路線規劃，車上空位查詢，墾丁交通資訊一把抓- 立即預訂車票-" />
}

<style>
  .path-tut-mobile {
    display: none;
  }
  
  .plannow {
    text-align: center;
    /*background: url(/images/plannow.png);*/
    background-color: rgba(255,255,255,.8);
    width: 100%;
    height: 209px;
    background-size: cover;
    background-position: center center;   
  }
  .content-wrapper.main-content {
    /*background-image: url(../images/navigation/navigation3.jpg);*/
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;

  }
  @@media (max-width: 767px) {
    .path-tut-mobile {
      display: block;
    }
    
    .path-tut{
      display: none;
    }
    
  }

</style>



<div class="">
  <div class="container route-planner" style="margin-top:0;">
    @* <div style="font-size: 24px;color:#8791da;padding-top: 20px;font-weight: 200;">ROUTE PLANNER</div> *@
    <h2 class="l-h2">路線規劃</h2>
    @* <div style="color: #f3892f;padding: 20px;"> - 立刻規劃你的行程路線 -</div> *@
  </div>
  <div class="container banner">
    <img class="path-tut" src="/images/path-tut.png" alt="">
    <img class="path-tut-mobile" src="/images/path-tut-mobile.png" alt="">
  </div>
</div>
  
<div class="plannow">
  <div style="color: black;font-size: 30px;font-weight: 200;padding: 40px;">PLAN NOW</div>
  <a href="/TravelPlan/overview" class="button" style="background:#5e6bd1;padding:15px;">  立即規劃行程</a>
</div>