Areas/English/Controllers/TravelPlanController.cs
using System;
using System.Collections.Generic;
using System.Device.Location;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fun2tw.Controllers;
using Fun2tw.Models;
using Fun2twModels.Models;
using MvcPaging;
using Newtonsoft.Json;

namespace Fun2tw.Areas.English.Controllers
{
    public class TravelPlanController : _BaseController
    {
        private BackendContext _db = new BackendContext();
        private const int DefaultPageSize = 16;
        //
        // GET: /TravelPlanController/

        public ActionResult Index(int? page, FormCollection fc,int id=0)
        {
            //記住搜尋條件
            GetCatcheRoutes(page, fc);

            //取得正確的頁面
            int currentPageIndex = getCurrentPage(page, fc);

            var travelplans = _db.TravelPlans.Where(x => x.CategoryId == 2 || x.CategoryId == 7).OrderByDescending(p => p.InitDate).AsQueryable();
            ViewBag.CategoryId = new SelectList(_db.TravelPlanCatalogs.Where(x => x.id == 2 || x.id == 7).OrderBy(p => p.InitDate), "id", "Subject");
            
            if (hasViewData("SearchBySubject"))
            {
                string searchBySubject = getViewDateStr("SearchBySubject");
                travelplans = travelplans.Where(w => w.Subject.Contains(searchBySubject));
            }
            if (id != 0)
            {
                switch (id)
                {
                    case 1:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("枋山鄉"));
                        ViewBag.URLCategory = "枋山鄉";
                        break;
                    case 2:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("獅子鄉"));
                        ViewBag.URLCategory = "獅子鄉";
                        break;
                    case 3:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("滿州鄉"));
                        ViewBag.URLCategory = "滿州鄉";
                        break;
                    case 4:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("牡丹鄉"));
                        ViewBag.URLCategory = "牡丹鄉";
                        break;
                    case 5:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("恆春鎮"));
                        ViewBag.URLCategory = "恆春鎮";
                        break;
                    case 6:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("車城鄉"));
                        ViewBag.URLCategory = "車城鄉";
                        break;
                    case 7:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("生態"));
                        ViewBag.URLCategory = "生態之旅";
                        break;
                    case 8:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("親水"));
                        ViewBag.URLCategory = "親水之旅";
                        break;
                    case 9:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("休閒遊憩之旅"));
                        ViewBag.URLCategory = "休閒遊憩之旅";
                        break;
                    case 10:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("古蹟"));
                        ViewBag.URLCategory = "古蹟文化之旅";
                        break;
                    case 11:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("景觀之旅"));
                        ViewBag.URLCategory = "景觀之旅";
                        break;
                    case 12:
                        travelplans = travelplans.Where(w => w.TagInfo.Contains("溫泉"));
                        ViewBag.URLCategory = "溫泉其他之旅";
                        break;
                }
            }

            //            ViewBag.Subject = Subject;
            return View(travelplans.Where(x=>x.TravelPlanImages.Count>0).OrderByDescending(p => p.TravelPlanImages.Count).ToPagedList(currentPageIndex, DefaultPageSize));
        }

        public ActionResult Search(int? page, FormCollection fc, string[] Category = null, string[] Town = null,int index=0)
        {
            //記住搜尋條件
            GetCatcheRoutes(page, fc);


            //取得正確的頁面
            int currentPageIndex = getCurrentPage(page, fc);

            var travelplans = _db.TravelPlans.OrderByDescending(p => p.InitDate).AsQueryable();

            //if (hasViewData("SearchBySubject"))
            //{
            //    string searchBySubject = getViewDateStr("SearchBySubject");
            //    shopinfos = shopinfos.Where(w => w.Subject.Contains(searchBySubject));
            //}
            string[] Towns = new string[] { };
            if (Town != null)
            {
                Towns = Town;
            }
            else if (Session["travelplansTown"] != null)
            {
                Towns = (string[])Session["travelplansTown"];
            }
            string[] Categorys = new string[] { };
            if (Category != null)
            {
                Categorys = Category;
            }
            else if (Session["travelplansCategory"] != null)
            {
                Categorys = (string[])Session["travelplansCategory"];
            }

            if (Towns.Length > 0)
            {
                travelplans = travelplans.Where(x => x.CategoryId == 0);
                foreach (string item in Towns)
                {
                    //Linq或的語法
                    travelplans = travelplans.Concat(_db.TravelPlans.Where(x => x.TagInfo.Contains(item)));
                }
            }
            var travelplans1 = _db.TravelPlans.Where(x => x.CategoryId == 0).OrderByDescending(p => p.InitDate).AsQueryable();
            if (Categorys.Length > 0)
            {
                foreach (string item in Categorys)
                {
                    //Linq或的語法
                    travelplans1 = travelplans1.Concat(_db.TravelPlans.Where(x => x.TagInfo.Contains(item)));
                }
            }
            if (travelplans1.Any())
            {
                travelplans = travelplans.Intersect(travelplans1);
            }

            travelplans = travelplans.Distinct();


            ViewBag.ClassId = _db.TravelPlanCatalogTags.OrderBy(x => x.ListNum).ToList();
            ViewBag.selectClassId = Categorys;
            ViewBag.selectTown = Towns;
            Session["travelplansCategory"] = Categorys;
            Session["travelplansTown"] = Towns;


            //            ViewBag.Subject = Subject;
            return View(travelplans.Where(x => x.TravelPlanImages.Count > 0).OrderByDescending(p => p.TravelPlanImages.Count).ToPagedList(currentPageIndex, DefaultPageSize));
        }
      
        [HttpPost]
        public ActionResult Search(int? page, FormCollection fc, string[] Category = null, string[] Town = null)
        {
            //記住搜尋條件
            GetCatcheRoutes(page, fc);


            //取得正確的頁面
            int currentPageIndex =1;

            var travelplans = _db.TravelPlans.OrderByDescending(p => p.InitDate).AsQueryable();

            //if (hasViewData("SearchBySubject"))
            //{
            //    string searchBySubject = getViewDateStr("SearchBySubject");
            //    shopinfos = shopinfos.Where(w => w.Subject.Contains(searchBySubject));
            //}
            string[] Towns = new string[] { };
            if (Town != null)
            {
                Towns = Town;
            }
           
            string[] Categorys = new string[] { };
            if (Category != null)
            {
                Categorys = Category;
            }
           

            if (Towns.Length > 0)
            {
                travelplans = travelplans.Where(x => x.CategoryId == 0);
                foreach (string item in Towns)
                {
                   
                    //Linq或的語法
                    travelplans = travelplans.Concat(_db.TravelPlans.Where(x => x.TagInfo.Contains(item)));
                }
            }
            var travelplans1 = _db.TravelPlans.Where(x => x.CategoryId == 0).OrderByDescending(p => p.InitDate).AsQueryable();
            if (Categorys.Length > 0)
            {

                foreach (string item in Categorys)
                {
                    //Linq或的語法
                    travelplans1 = travelplans1.Concat(_db.TravelPlans.Where(x => x.TagInfo.Contains(item)));
                }
            }
            if (travelplans1.Any())
            {
                travelplans = travelplans.Intersect(travelplans1);
            }

            travelplans = travelplans.Distinct();


            ViewBag.ClassId = _db.TravelPlanCatalogTags.OrderBy(x => x.ListNum).ToList();
            ViewBag.selectClassId = Categorys;
            ViewBag.selectTown = Towns;
            Session["travelplansCategory"] = Categorys;
            Session["travelplansTown"] = Towns;


            //            ViewBag.Subject = Subject;
            //return View(travelplans.Where(x => x.TravelPlanImages.Count > 0).OrderByDescending(p => p.TravelPlanImages.Count).ToPagedList(currentPageIndex, DefaultPageSize));
            return RedirectToAction("Search");
        }

        public ActionResult Details(int id = 0)
        {
            TravelPlan travelPlan = _db.TravelPlans.Find(id);
            if (travelPlan == null)
            {
                //return HttpNotFound();
                return View();
            }
            if (Session["history"] != null)
            {
                List<TravelPlan> travelPlans = (List<TravelPlan>) Session["history"];
                if (travelPlans.All(x => x.Id != id))
                {
                    travelPlans.Add(travelPlan);
                }
                Session["history"] = travelPlans;

            }
            else
            {
                List<TravelPlan> travelPlans = new List<TravelPlan>();

Areas/English/Views/TravelPlan/Details.cshtml
@using Fun2twModels.Models
@model Fun2twModels.Models.TravelPlan
@{
    ViewBag.Title = @Model.Subject;
}

@{
    List<TravelPlan> travelPlans = (List<TravelPlan>)Session["history"];
    String navigation = "Navigation";
    var addressList = (List<Navigation>)Session["addressList"];
    if (addressList != null && addressList.Count > 0)
    {
        navigation += "(" + addressList.Count.ToString() + ")";
    }
}

<div class="container l-white">
    <h2 class="l-titles" style="margin-bottom: 0;"><a href="/English/TravelPlan/overview">Recommend Scenic Spots</a>
        @*> <a href="/English/TravelPlan/index/@ViewBag.townID">@Model.Town</a>*@ 
        > @Model.Subject

        <a class="btn btn-primary" style="cursor: pointer;" id="add" onclick="addLocation('@Model.Subject', '@Model.Street','@Model.Lon','@Model.Lat');">Add to Route Plan List</a> 

        @Html.ActionLink(@navigation, "SortLocation", "Navigation", null, new { id = @"navigation",@class="btn btn-cyan" }) 

        <input type="button" onclick="history.back();" class="btn btn-success" value="back"> 


        </h2>
    <div class="flexslider">
       
        <ul id="slider" class="slides theme-default">
             @foreach (var img in Model.TravelPlanImages)
        {
            <li>
            <img src="~/upfiles/@img.Folder@img.FileName"/>
            </li>
        }
        
        </ul>
</div>
       <!--  <ul class="nav nav-tabs l-tab" role="tablist">
            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">景點介紹</a></li>
            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">其他資訊</a></li>
        </ul> -->
        
        <div class="tab-content news-content">
            <div role="tabpanel" class="tab-pane active" id="home">
                 @* <h1 class="l-titles">&nbsp;&nbsp;@Model.Subject   </h1> *@

                 @* <span id="notadd">此景點目前不支援路線規劃</span> *@

   

    
                <div style="display: none;">

                    @if (Model.TravelPlanImages.Count > 0)
                    {
                        <img src="~/upfiles/@Model.TravelPlanImages.FirstOrDefault().Folder@Model.TravelPlanImages.FirstOrDefault().FileName"/>
                    }
                </div>
                
                <div style="margin-bottom: 10px">
                    @Html.Raw(Model.Article)



                    @Model.Special

                    @if (!string.IsNullOrEmpty(@Model.TipsInfo))
                    {
                        <h3 class="l-detail-title"><em>Traffic</em>
                        </h3>
                        @Model.TrivalInfo
                    }


                    @if (!string.IsNullOrEmpty(@Model.TipsInfo))
                    {
                        <h3 class="l-detail-title"><em>Important Information

</em>
                        </h3>
                        @Html.Raw(Model.TipsInfo)
                    }



                    @if (!string.IsNullOrEmpty(@Model.Town))
                    {
                        <h3 class="l-detail-title"><em>location</em>
                        </h3>
                        @Model.Town
                    }

                    @if (!string.IsNullOrEmpty(@Model.Tel))
                    {
                        <h3 class="l-detail-title"><em>phone</em>
                        </h3>
                        @Model.Tel
                    }


                    @if (!string.IsNullOrEmpty(@Model.Fax))
                    {
                        <h3 class="l-detail-title"><em>Fax</em>
                        </h3>
                        @Model.Fax
                    }

                    @if (!string.IsNullOrEmpty(@Model.WebSite))
                    {
                        <h3 class="l-detail-title"><em>Website</em>
                        </h3>
                        @Model.WebSite
                    }

                    @if (!string.IsNullOrEmpty(@Model.Email))
                    {
                        <h3 class="l-detail-title"><em>E-mail</em>
                        </h3>
                        @Model.Email
                    }

                    @if (!string.IsNullOrEmpty(@Model.Street))
                    {
                        <h3 class="l-detail-title"><em>Adress</em>
                        </h3>
                        @Model.Street
                    }

                    @if (!string.IsNullOrEmpty(@Model.ServiceTime))
                    {
                        <h3 class="l-detail-title"><em>Hours of opening</em>
                        </h3>
                        @Model.ServiceTime
                    }

                    @if (!string.IsNullOrEmpty(@Model.ConsumerMode))
                    {
                        <h3 class="l-detail-title"><em>Fare Details</em>
                        </h3>
                        @Model.ConsumerMode
                    }
                     <h3 class="l-detail-title"><em>Attractions Browsing History</em></h3>
                    @if (travelPlans.Count > 0)
                    {
                        foreach (var item in travelPlans)
                        {
                            <p>
                                <a href="/English/TravelPlan/Details/@item.Id">@item.Subject</a>
                            </p>
                            
                        }

                    }
                    else
                    {
                        <span>No Record</span>
                    }
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="profile">
               


            </div>
             <iframe title="警勤區查詢服務" width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src='http://maps.google.com.tw/maps?f=q&hl=zh-TW&geocode=&q=@(Model.Subject)&z=16&output=embed&t='></iframe>
        </div>

        <div>
            
           
        </div>
    </div>
    
    
<div class="text-center m1">
    <input type="button" onclick="history.back();" class="btn btn-cyan" value="Back to List">
</div>



</div>
<script>
    function addLocation(subject, address,lon,lat) {
        //alert("add  " + addressId + address);
        $.post('@Url.Content("~/Navigation/AddLocation")', { Subject: subject, Address:address,Lon:lon,Lat:lat })
            .done(function (data) {
                //alert(data);
                if (data === 'duplicate') {
                    alert('Fail!\n' + subject + ' Already in the navagation list.');
                } else if (data === 'over') {
                    alert('Fail!\n' + 'Google Map only allowed navigation under 10 spots.');
                } else {
                    //alert($('#navigation').text());
                    $('#navigation').text('Navigation' + '(' + data + ')');
                    $('.jq-num').text(data);
                    alert(subject + ' Done!');
                }
            });

    }
</script>

<script>

    function initMap() {
        var directionsService = new google.maps.DirectionsService;
        var waypts = [];
        waypts.push({
            address: '@Model.Subject',
             lat: '@Model.Lat',
             lng: '@Model.Lon'
         });
         displayRoute('屏東火車站', '台東火車站', directionsService, waypts, '@Model.Id');
     }

     function displayRoute(origin, destination, service, waypoints) {
         var waypts = [];
         var checkboxArray = waypoints;
         for (var i = 0; i < checkboxArray.length; i++) {
             if (checkboxArray[i].lat.length > 0 && checkboxArray[i].lng.length > 0) {
                 waypts.push({
                     location: new google.maps.LatLng(checkboxArray[i].lat, checkboxArray[i].lng),
                     stopover: true
                 });
             } else {
                 //alert(checkboxArray[i].address);
                 waypts.push({
                     location: checkboxArray[i].address,
                     stopover: true
                 });
             }
         }

         service.route({
             origin: origin,
             destination: destination,
             //waypoints: [{ location: waypoint }],
             waypoints: waypts,
             travelMode: google.maps.TravelMode.DRIVING,
             avoidTolls: true
         }, function (response, status) {
             if (status === google.maps.DirectionsStatus.OK) {
                 //alert("OK");
                 $('#add').show();
                 $('#notadd').hide();
             } else {
                 //alert("error");
                 $('#add').hide();
                 $('#notadd').show();
             }
         });
     }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHNgGDd59BQqpVBV6Hza24iIgfZTEwjZA&signed_in=true&callback=initMap&region=TW" async defer></script>

Areas/English/Views/TravelPlan/Index.cshtml
@using MvcPaging
@using Fun2tw.Helpers
@model IPagedList<Fun2twModels.Models.TravelPlan>
@{
    ViewBag.Title = "旅遊景點介紹";
}
<div class="l-banner"  style="background: url(/images/banner-travel-bg.png)" >
  <img src="/images/banner-travel.png">
</div>
<div class="container l-white ">


   @using (Html.BeginForm("index", "TravelPlan", new { page = 1 }))
   {
 <h2 class="l-titles l-titles-indent">
     <a href="/English/TravelPlan/overview">景點導覽</a> 
     @*> @ViewBag.URLCategory <span style="line-height:1">POPULAR ATTRACTION</span>*@ 
     
 </h2>
<div class="l-titles-form form-inline" >
       景點查詢： @Html.TextBox("SearchBySubject",null,null,new{@class="form-control"})
       <input type="submit" class="btn btn-primary" value="搜尋"/>

     </div>
    

    
}
<div class="">
    <div class="">
        <div class="">
            <ul class="l-card  l-card-nogutter">
    @foreach (var item in Model) {
         <li class="col-md-3 col-xs-12">
         
          


           <div class="l-card-main">
               <div class="l-card-image">
                    <a href="/English/TravelPlan/Details/@item.Id">
               @if (item.TravelPlanImages.Count>0)
                {
                    if (item.TravelPlanImages.FirstOrDefault().Folder == "images/")
                    {
                        <img style="height: 150px !important;" src="~/upfiles/@(item.TravelPlanImages.FirstOrDefault().Folder)s@(item.TravelPlanImages.FirstOrDefault().FileName)"/>
                    }
                    else
                    {
                         <img style="height:150px !important; " src="~/upfiles/@item.TravelPlanImages.FirstOrDefault().Folder@item.TravelPlanImages.FirstOrDefault().FileName" />
                    }
                   
                }
                   </a>
               </div>
               <div class="l-card-content">
              <h2>@item.Subject</h2>
              </div>
           </div>
        </li>
    
}
</ul>
        </div>
    </div>
</div>



<div class="l-pagination">
<div class="pagination">
    @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount)
</div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker();

        });
    </script>
}

</div>

Areas/English/Views/TravelPlan/OverView.cshtml
@using Fun2twModels.Models

@{
    ViewBag.Title = "景點介紹";
    List<TravelPlanCatalogTag> travelPlanCatalogTags = ViewBag.ClassId;
}

 <style>
        span.Category {
          padding: 10px 0;
          font-size: 20px;
          display: block;
        }
        .checkbox-inline {
          color: gray;
        }
        .news-content{
          float: left;
          width: 100%;
        }
        .map-svg {
          padding: 2em;
          float: left;
          width: 80%;
        }
        .clear {
          clear: both;
        }
        
        @@media (max-width: 768px) {
            .news-content,.map-svg {
                float: none;
                width: 100%;
            }
            .checkbox-inline {
              display: inline-block;
            }
            .l-card {
                display: block !important;
            }
            .map-svg {
                display: none;
            }
        }
        area:focus { border: none }img.map, map area {
                                       outline: none;
                                   }
    </style>
  <script>
    $(document).ready(function(){
      $('.panel-body span i').eq(0).addClass('fa-location-arrow');
      $('.panel-body span i').eq(1).addClass('fa-home');
      $('.panel-body span i').eq(2).addClass('fa-shopping-bag');
      $('.panel-body span i').eq(3).addClass('fa-cutlery');
      $('.panel-body span i').eq(4).addClass('fa-globe');
     
     
    })
  </script>


<div class="container l-white">
 <h2 class="l-h2" style="border:0;background: none;line-height: 1.5em;"> Recommend Scenic Spots </h2>
    <div class="news-content" style="">
     

      <div class="">
            @using (Html.BeginForm("Search", "TravelPlan"))
            {
                <div class="">
               @foreach (var category in travelPlanCatalogTags.Where(x => x.ParentId == null))
               {

                   <span class="Category">
        <i class="fa" aria-hidden="true"></i> @category.SubjectEnglish：
      </span>
                   string itemName = "Category";
                   if (category.Subject == "所在區域")
                   {
                       itemName = "Town";
                   }

                   foreach (var item in category.ChildCategory)
                    {
                
                         <label class="checkbox-inline">
                           
                                <input type="checkbox" id="inlineCheckbox@(item.Id)" name="@(itemName)" value="@item.Subject">
                                      @item.SubjectEnglish

                         </label>
                     }
                  

              <br>
               }



   
              <div class="m1">
                  <input type="submit" class="btn btn-primary " value="Search">
              </div>
          </div>
            }
          
      </div>
    </div>
    
    @* <div class="map-svg" style="text-align: center">

        <img src="/images/mad-edit.png" alt="" usemap="#Map"/>
        <map name="Map" id="Map">
            <area alt="" title="" href="/English/TravelPlan/index/6" shape="poly" coords="273,91,587,299,534,182,809,338,493,350,344,345,302,428,375,88,423,188,282,99,309,85,353,126,366,139,307,310,289,439"/>
            <area alt="" title="" href="/English/TravelPlan/index/4" shape="poly" coords="394,88,432,178,633,107,1074,198,1080,85,800,220,852,89,988,89,869,274,470,86,518,40,658,55,774,106,841,150,901,103,859,313"/>
            <area alt="" title="" href="/English/TravelPlan/index/5" shape="poly" coords="285,471,410,392,593,415,601,361,484,784,591,575,850,600,1041,795,438,787,383,825,565,575,329,696,308,810,378,821,415,878,673,867,269,876,346,806,376,789,441,719,509,640,350,610,282,641,319,683,366,683,617,368,641,394,690,402,569,357,288,639,382,653,371,719,303,745,421,594,549,449,563,420,252,559,268,599,292,620,327,581,390,524,427,492,285,537"/>
            <area alt="" title="" href="/English/TravelPlan/index/3" shape="poly" coords="1078,213,956,205,924,308,730,388,601,549,957,580"/>
            
        </map>
    </div> *@
    <div class="clear"></div>
   

   @*  <ul class="l-card  l-card-nogutter" style="display: none">
        
      
        <li class="col-md-6 col-xs-12"><a href="/TravelPlan/index/6"><img src="/images/pingtung-7.png"></a></li>
        <li class="col-md-6 col-xs-12"><a href="/TravelPlan/index/5"><img src="/images/pingtung-8.png"></a></li>
        <li class="col-md-6 col-xs-12"><a href="/TravelPlan/index/3"><img src="/images/pingtung-9.png"></a></li>
        <li class="col-md-6 col-xs-12"><a href="/TravelPlan/index/4"><img src="/images/pingtung-10.png"></a></li>
    </ul> *@
</div>
<!--  <a href="/TravelPlan/index/7">生態之旅</a>
        <a href="/TravelPlan/index/8">親水之旅</a>
        <a href="/TravelPlan/index/9">休閒遊憩之旅</a>
        <a href="/TravelPlan/index/10">古蹟文化之旅</a>
        <a href="/TravelPlan/index/11">景觀之旅</a>
        <a href="/TravelPlan/index/12">溫泉其他之旅</a>
 -->


   @section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    
}

Areas/English/Views/TravelPlan/Search.cshtml
@using MvcPaging
@using Fun2tw.Helpers
@using Fun2twModels.Models
@model IPagedList<Fun2twModels.Models.TravelPlan>
@{
    ViewBag.Title = "旅遊景點介紹";
    List<TravelPlanCatalogTag> travelPlanCatalogTags = ViewBag.ClassId;
    string[] selectClassId = ViewBag.selectClassId ?? new string[] { "" };
    string[] selectTown = ViewBag.selectTown ?? new string[] { "" };
}

<div class="container l-white ">


  <div class="news-content" style="padding-top:0;">
    <div class="">
          @using (Html.BeginForm())
          {
              <div class="panel-body">
             @foreach (var category in travelPlanCatalogTags.Where(x => x.ParentId == null))
             {
               
                 <span class="Category">
      <i class="fa" aria-hidden="true"></i> @category.SubjectEnglish：
    </span>
                 string itemName = "Category";
                 if (category.Subject == "所在區域")
                 {
                     itemName = "Town";
                 }

                 foreach (var item in category.ChildCategory)
                  {
                    
                       <label class="checkbox-inline">
                         
                               @if (selectClassId.Contains(item.Subject) || selectTown.Contains(item.Subject) )
                                {
                                    <input type="checkbox" id="inlineCheckbox@(item.Id)" name="@(itemName)" value="@item.Subject" checked="checked">
                                    @item.SubjectEnglish
                                }
                                else
                                {
                                    <input type="checkbox" id="inlineCheckbox@(item.Id)" name="@(itemName)" value="@item.Subject">
                                    @item.SubjectEnglish
                                }
                           
                         
                         

                       </label>
                   }
                

            <br>
             }



 
            <div class=" ">
                <input type="submit" class="btn btn-primary " value="Search">
            </div>
        </div>
          }
        
    </div>
  </div>
 
<div class="wrap-card">
    <div class="">
        <div class="">
            <ul class="l-card">
    @foreach (var item in Model) {
         <li class="col-md-6 col-xs-12">
         
          


           <div class="l-card-main">
               <div class="l-card-image">
                    <a href="/English/TravelPlan/Details/@item.Id">
               @if (item.TravelPlanImages.Count>0)
                {
                    if (item.TravelPlanImages.FirstOrDefault().Folder == "images/")
                    {
                        <img src="~/upfiles/@(item.TravelPlanImages.FirstOrDefault().Folder)s@(item.TravelPlanImages.FirstOrDefault().FileName)"/>
                    }
                    else
                    {
                         <img src="~/upfiles/@item.TravelPlanImages.FirstOrDefault().Folder@item.TravelPlanImages.FirstOrDefault().FileName" />
                    }
                   
                }
                   </a>
               </div>
               <div class="l-card-content">
              <h2>@item.Subject</h2>
              </div>
           </div>
        </li>
    
}
</ul>
        </div>
    </div>

    <div class="l-pagination">
    <div class="pagination">
        @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount)
    </div>
    </div>
</div>

<style>
.l-card-main {
  position: relative;
  height: 300px;
  overflow: hidden;
  background: none;
  margin: 10px;
}
.l-card h2 {
  padding: 10px;
}
.l-card-image {
  border-radius: 0; 
  background: #000;

}
.l-card-content {
  position: absolute;
  z-index: 2;
  bottom: 0;
  width: 100%;
  background: rgba(0,0,0,.6);
  color: white;
  border-radius: 0; 
  padding: 0;
}
.pagination a,.pagination span {
  border: 0;
  color: #bbbbbb;
}

.pagination a:hover,
.pagination a:focus,
.pagination span:hover,
.pagination span:focus,
.pagination .current {
  color: white;
  background: #68d1df;
}

        span.Category {
          font-size: 20px;
          display: block;
        }
        .checkbox-inline {
          color: gray;
          display: block;
        }
        .news-content{
          float: left;
          width: 30%;
        }
        .wrap-card {
          padding: 35px 0;
          float: left;
          width: 70%;
        }
        .clear {
          clear: both;
        }
        @@media (max-width: 768px) {
            .news-content,.wrap-card {
                float: none;
                width: 100%;
            }
            .checkbox-inline {
              display: inline-block;
            }
           
        }
    </style>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker();

        });
    </script>
}

</div>